### ISSUE TITLE
Workspaces API should show correct opening times for all libraries

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/uclapi#1026]
Some libraries, such as the UCL School of Pharmacy Library, actually have accurate (or near enough accurate) opening hours that could be passed straight through to users.

Others, such as the UCL Main Library, do not. We should patch up these libraries with truthful opening hours so that developers can pass this data through to users.

We should also ensure that opening hours are correct for each day (e.g. Sunday hours on a Sunday should be returned).

We could actually set up a separate endpoint for Library Opening Hours. The concern I have is in maintaining this. One option would be if we wrote a scraper and combined the data on the cron server each hour (or on Lambda), but this sounds like a lot of faff.

Opinions wanted 🙌

**Comment by hueyy** [comment]
Yes! This would be really useful. AFAIK the only reliable source of info regarding opening hours is the library website, i.e. [https://www.ucl.ac.uk/library/opening-hours](https://www.ucl.ac.uk/library/opening-hours).

But scraping does sound rather messy since the data pretty unstructured:

![image](https://user-images.githubusercontent.com/6523121/52965573-051a4300-339d-11e9-935d-4e9b4f26c3aa.png)
![image](https://user-images.githubusercontent.com/6523121/52965582-0d727e00-339d-11e9-8d1a-de34ece3dd44.png)

There are different opening hours for different parts of some libraries, there are special circumstances where the opening hours change (during the Christmas break, the first Thursday of each month, etc.)

If and when the library staff rephrase the text stating the opening hours, our scrapers will probably break :/

**Comment by ChristopherHammond13** [comment]
Yeah it looks like we'll have to `lxml` the hell out of this one.

I'm thinking that we could cache it in Redis, but I'm not sure of the best way to do that yet. We may have to create a map between each library and the opening hours, and filter the libraries based on the ones we know to be real. I'll investigate...

**Comment by hueyy** [comment]
Following our discussion during Chris's handover, I assume we're not proceeding with this? At the most we'll relegate this to the experimental UCL API, i.e. UCL API Labs or something.
