### ISSUE TITLE
Provide Coordinates of Each Workspaces Survey

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/uclapi#1165]
This would help apps like UCL Assistant sort libraries by proximity to user, and navigate users to study space buildings.

**Comment by hueyy** [comment]
Just to clarify, this would involve adding location data (lat, lon at least, address etc is a plus) to the survey data returned by the various workspace endpoints (e.g. `/workspaces/sensors/summary`)

**Comment by zipy124** [comment]
Should have this done by tonight, will not be the most elegant solution though, since manual data entry is needed because we don't have any databases containing some of the buildings as they don't use the same room bookings system :( . We could get less accurate results by using the site they are closest to/in however but i'd rather maintain accuracy.
