### ISSUE TITLE
Timetable by module returns dates not in order 

### ISSUE THREAD

**Issue by achen04** [uclapi/uclapi#121]
Sample return (objects are not in order by date): 

```
{ ok: true,
  timetable: 
   { '2018-01-16': [ [Object] ],
     '2018-02-20': [ [Object] ],
     '2018-01-25': [ [Object] ],
     '2018-02-27': [ [Object] ],
     '2018-03-08': [ [Object] ],
     '2018-03-06': [ [Object] ],
     '2018-02-22': [ [Object] ],
     '2018-03-22': [ [Object] ],
     '2018-03-01': [ [Object] ],
     '2018-01-30': [ [Object] ],
     '2018-02-01': [ [Object] ],
     '2018-01-09': [ [Object] ],
     '2018-01-11': [ [Object] ],
     '2018-03-20': [ [Object] ],
     '2018-03-15': [ [Object] ],
     '2018-02-08': [ [Object] ],
     '2018-03-13': [ [Object] ],
     '2018-01-23': [ [Object] ],
     '2018-02-06': [ [Object] ],
     '2018-01-18': [ [Object] ] } }
```

**Comment by ChristopherHammond13** [comment]
Due to how dictionaries work we will not be fixing this at this time I'm afraid :( It can be easily done on the frontend though so that it does not slow does requests for everybody.

Unfortunately, the data is not stored in chronological order in the database we pull data from so it isn't possible to build the data structure up in a good order so we would have to (rather hackily!) sort it after the fact. Apologies for this :/
