### ISSUE TITLE
API should not set cookies

### ISSUE THREAD

**Issue by cbetta** [uclapi/uclapi#130]
Currently the API is setting cookies in the response headers.

```sh
> curl -i https://uclapi.com/roombookings/equipment?token\=uclapi-XXXX
Set-Cookie: __cfduid=dad563c84327467955b6b....; expires=Tue, 09-Oct-18 10:21:51 GMT; path=/; domain=.uclapi.com; HttpOnly
Set-Cookie: AWSALB=va5pX0q28lpPKwmbj/VissT3VRkYAAWqKqsEnlIQscOMERD7dxJE/IZGWKAjjhw7PorbrXynDq3eFtHWd...; Expires=Mon, 16 Oct 2017 10:21:51 GMT; Path=/
```

Cookies do not make sense within the context of an API. Consider disabling the cookie feature for the API endpoints. You might also be able to use cloudflare to strip the cookies in transport, but ideally this should happen in the app.

**Comment by ChristopherHammond13** [comment]
Interesting.

It looks like the `__cfduid` cannot be removed according to this post: https://github.com/mozilla/http-observatory/issues/121
It seems to be for CloudFlare's proxy.

The `AWSELB` one is for our elastic load balancer. We need host/session affinity enabled for the Shibboleth login to work properly (due to Shibboleth recommending strongly against clustering it, and instead setting it up individually on each host with no shared memory). It feels gross doing this, but it seems to be the only realistic option without over-engineering it: https://wiki.shibboleth.net/confluence/plugins/servlet/mobile?contentId=4358163#content/view/4358163

I'll take a look into them anyway to see if there's a way we can stop them being applied to endpoints but a cursory Google of these cookies doesn't look hopeful.

Is there a specification / set of tips we should follow to eliminate these cookies?

**Comment by cbetta** [comment]
Ah ok they aren't coming from your app. That's good at the least. I've only ever used AWS CloudFront, and they allow you to drop most cookies.

**Comment by ChristopherHammond13** [comment]
The `AWSELB` one could be solved by having two Shibboleth login servers then authenticating Django behind the scenes which would be run on two other load balanced servers without session affinity (thus removing the need for this header). I would be concerned about the cost/benefit analysis of this though, at this point.

I have a number of ideas about how our deployment processes could be improved and we could do this at that stage but it's unlikely to be done ASAP. @wilhelmklopp, opinions?

**Comment by ChristopherHammond13** [comment]
Yes, correct, the app doesn't produce cookies except for:
- CSRF Protected views with forms to protect against forged submissions
- The Dashboard uses a session cookie so that once the user is logged in via Shibboleth they remain logged in until that cookie is cleared

**Comment by cbetta** [comment]
I have only an inkling what you're on about. It's not a major issue, just a nicety.

**Comment by wilhelmklopp** [comment]
I agree it'd be nice to drop the cookies somehow for API views, but as pointed out, not really a priority at the moment. 

Thanks for pointing this out @cbetta :)

**Comment by cbetta** [comment]
So has this been fixed or just closed? Would be good to mark it as "wont-fix" or something for now :)

**Comment by ChristopherHammond13** [comment]
@cbetta sorry, this should clarify things better!

I had some more thoughts about it and there _are_ ways to fix this but not without significantly rearchitecting our API so unfortunately fixing this has fallen over at the cost/benefit analysis :( Thank you for the feedback though and keep it coming!
