### ISSUE TITLE
caching script progress bars duplicate and display wrong

### ISSUE THREAD

**Issue by zipy124** [uclapi/uclapi#1300]
Unfortunately the developers of the progress bar library we use have concurrency bugs in their library. (see https://github.com/tqdm/tqdm/issues/285 and https://github.com/tqdm/tqdm/issues/407 ) We will have to implement our own lock system.

**Comment by Feverfew** [comment]
I think at this point we should get rid of the progress bars? They make no sense in production and we don't need stuff breaking just because of a feature only desirable in development anyway.

Maybe we should consider using logs: in debug mode they print to screen, in production they go to a log file. This would be good for both development and production, so that we always know the performance of updating gencache.

**Comment by zipy124** [comment]
Thats actually exactly what we do, we can enable a -debug flag to show progress bars, by default they do not show.

**Comment by zipy124** [comment]
Closing this issue as can't fix due to the linked issues. Synchronizing them would use up far too many cpu cycles for no reason.
