### ISSUE TITLE
Oauth 500

### ISSUE THREAD

**Issue by balping** [uclapi/uclapi#1602]
Hi,

There were several people reporting issues to me when logging in with oauth and receiving a server error 500 message.

It works for most people using my app, I'm not sure what's the reason it fails for some.

If you need help digging up the log files, I can provide some confidential information (ie names, or ucl email addresses for failed accounts), please PM me in this case. 

![Screenshot](https://user-images.githubusercontent.com/5840038/64558272-c56c7600-d343-11e9-8b5c-7d4857a6201e.JPG)

**Comment by hueyy** [comment]
The persons reporting 500s are most likely students enrolling in AY19/20. Since they have not fully matriculated yet, UCL is not yet passing us all the information we need.

We're working to figure out what information is missing, and to throw a more helpful error message. But for the time being, you might want to add a warning to your app.

**Comment by balping** [comment]
OK, thanks
