### ISSUE TITLE
OAuth Error 403 denied

### ISSUE THREAD

**Issue by henryz00** [uclapi/uclapi#1628]
**Describe the bug**
When newly enrolled students trying to logging using OAuth, the 403 denied error would occur saying "alumni are not permitted to use UCL Apps".

**To Reproduce**
It seems only new students who are just enrolled will have this problem if they are trying to OAuth.

**Expected behaviour**
They are expected to be able to login I guess.

**Screenshots**
![WechatIMG14005](https://user-images.githubusercontent.com/20445029/65315304-c006fb00-db8f-11e9-9b7f-6b22991131f6.png)

**Additional context**
This might be a problem after fixing the [error 500](https://github.com/uclapi/uclapi/issues/1602) bug.

**Comment by Feverfew** [comment]
Yes, this whole summer UCL's Shibboleth has been missing out header's completely which has been causing us significant pain. In this case, what's going on is the group's attribute is missing, which we used to interpret as the student is an alumni. However, UCL haven't sorted out the groups for freshers and so this is occurring to them as well. There's several ways to go about this. 

Firstly, if there is a way of determining if an account belongs to an alumnus, we switch to that method, and new students can log in whilst keeping alumni out. 

Otherwise, we'll have to have a tradeoff. Either we allow both alumni and new students to log in, or we allow neither of them, in which case I'll merge (once I edit it a bit) and deploy #1629 . I'll open a discussion with the rest of the team to come to a decision by tomorrow.

**Comment by Feverfew** [comment]
@henryz00 @balping does this #1631 sort this out for you? If so please close.

Note that if you only want students to access your app via OAuth please make use of the is_student attribute as noted here: https://uclapi.com/docs#oauth/user/data.

**Comment by henryz00** [comment]
Yes, it does. Thanks for sorting this out.

**Comment by balping** [comment]
Looks good, thanks.
