### ISSUE TITLE
JSON Keys should be static

### ISSUE THREAD

**Issue by tiferrei** [uclapi/uclapi#210]
Good morning,

I believe that even though there isn't a particular rule saying that JSON keys should be static and predictable in APIs, to facilitate parsing and creating expected models. Right now the `timetable` endpoints don't seem to do this, as they use the main key for the appointment day as its date:
```json
{
    "timetable":{
        "2018-01-29": [
            {
                "location": {
                    "address": [
                        "29 Gordon Sq",
                        "London",
                        "WC1H 0PP"
                    ],
                    "name": "Gordon House 106",
                    "sitename": "Gordon House",
                    "type": "CB",
                    "capacity": 50
                },
                "end_time": "18:00:00",
                "module": {
                    "module_id": "COMP3058",
                    "lecturer": {
                        "email": "ucacdgo@ucl.ac.uk",
                        "name": "GORSE, Denise (Dr)"
                    },
                    "name": "Artificial Intelligence and Neural Computing",
                    "course_owner": "COMPS_ENG",
                },
                "duration": 120,
                "start_time": "16:00:00"
            }
        ]
    },
    "ok": true
}
```

The use of `"2018-01-29"` as a Key seems wrong to me as it is itself a variable value. I can not program an API wrapper, or even an API client to expect any date in the form of YYYY-MM-DD without making everything confusing and overcomplicated. I believe that JSON keys should be static and predefined by the API. As so, I believe this would be better:

```json
{
    "timetable":[
        {
            "location":{
                "address":[
                    "29 Gordon Sq",
                    "London",
                    "WC1H 0PP"
                ],
                "name":"Gordon House 106",
                "sitename":"Gordon House",
                "type":"CB",
                "capacity":50
            },
            "end_time":"yyyy-MM-dd'T'HH:mm:ssZZZZZ",
            "module":{
                "module_id":"COMP3058",
                "lecturer":{
                    "email":"ucacdgo@ucl.ac.uk",
                    "name":"GORSE, Denise (Dr)"
                },
                "name":"Artificial Intelligence and Neural Computing",
                "course_owner":"COMPS_ENG"
            },
            "duration":120,
            "start_time":"yyyy-MM-dd'T'HH:mm:ssZZZZZ"
        }
    ],
    "ok":true
}
```
This way not only does the data become more predictable, we also use ISO 8601 timestamps which seems to be used on other endpoints. Without this change I can not add the Timetable endpoint to my framework, as I can't account for some random date being in the key value.

Thanks,
Tiago

**Comment by Faiz** [comment]
Hi Tiago,

Firstly, I believe ISO-8601 way of representing a date is yyyy-mm-dd which is exactly what we use as a key in the timetable object.

Using this schema for whole personal timetable was my decision. My preference was completely based on the use case approach as opposed to how we would make it work (nicely) for languages.  As I started thinking about it, I can see why this would make a little bit tricky to code in typed languages if you treat timetable as an object. After parsing, I believe using this structure would be more easy to deal with. I don't personally code in Swift, so I would give an example in Golang.

```
type timeTable struct {
    timetable map[string][]event,
    ok bool
}
```

Where `event` is a timetable event object which is static. Other way I was looking to implement this was similar to how we do room bookings event where we simply return an array of events. As given below,
 
```
type timeTable struct {
    timetable []dayEvents
    ok bool
}

type dayEvents struct {
    date string
    events []event
}
```
Where event is the single timetable event object, which is static.

But in terms of efficiency and use case, I would think a map makes more sense to do, as long as you don't intend to deal them as static objects.

We are going to implement more custom endpoints for timetable in coming weeks, your inputs are most welcome :) 

Thanks, 
Faiz

**Comment by tiferrei** [comment]
Hey, thanks for the fast reply.

I still don't see how I can efficiently program this in Swift. My framework is based on RequestKit, a Swift framework to build API wrappers. I [reached out to the lead dev]([https://github.com/nerdishbynature/RequestKit/issues/36) and he said this could maybe be possible to do in RequestKit but it would be extremely hacky, unstable and hard to test.

On the date format, I agree the date is already following `yyyy-MM-dd`, but if we didn't put the date in the key, this means we can put it in the start and end date as `yyyy-MM-dd'T'HH:mm:ssZZZZZ` like we do for other dates in other endpoints, providing more consistency. 
Also, many popular APIs seem to adopt this format like [Facebook Events](https://developers.facebook.com/docs/graph-api/reference/event/) or [Google Calendar](https://developers.google.com/google-apps/calendar/v3/reference/events)

**Comment by ChristopherHammond13** [comment]
I can se an argument for why this might be annoying from a generic parsing point of view. I think the reason we chose to do it like this is that it sort of forces a nice chronological output without the client having to sort it. One solution to this might be a parameter to request an unsorted output where we provide a `date` paremeter (as well as the `start_time` / `end_time`, probably in ISO8601). As with the current system, the date parameter would be the start date (in case of overnight events).

I think the issue you're having is more of a Swift issue than anything, as in most languages I would use a loop in the format:
```
for date, events in timetable:
    for event in events:
        # Do something with the events in that date
```
That said, it doesn't mean that what we are doing is necessarily the best, either, hence why I'm willing to do something about this. I realise that if you're not creating your own timetable viewer then this probably feels like an awkward way of parsing the data :)

**Comment by tiferrei** [comment]
Hey @ChristopherHammond13, indeed this is more of an issue with the way I'm handling JSON parsing, I just thought that for the sake of consistency, it would be good to have the API follow a style similar to what most popular APIs do.
Less time learning a new format = more time hacking amazing projects :)

**Comment by keelanfh** [comment]
@ChristopherHammond13 I like the idea of having the response sorted 😃, but the response coming from the API is not currently sorted chronologically, and this is to be expected, since it comes from a Python `dict`, which is inherently unordered. See the following:

```python
import requests
import re

params = {
  "token": UCLAPI_TOKEN,
  "modules": "COMP3095"
}

r = requests.get("https://uclapi.com/timetable/bymodule", params=params)

print(re.findall(r'\d+-\d+-\d+',r.text))
```
returns `['2017-10-03', '2017-12-07', '2017-12-14', '2017-11-30', '2017-10-06', '2017-10-13', '2017-11-23', '2017-11-16', '2017-10-19', '2017-10-10', '2017-11-02']`

and similarly, if a client then uses it as a Python `dict`:

```python
timetable = r.json()["timetable"]

print([x for x in timetable])
```

returns `['2017-10-03', '2017-12-07', '2017-12-14', '2017-11-30', '2017-10-06', '2017-10-13', '2017-11-23', '2017-11-16', '2017-10-19', '2017-10-10', '2017-11-02']`

It's probably very awkward to get your Python backend to output JSON with ordered keys, and in any case clients probably can't guarantee to retain that ordering (Python won't, at least. No idea about other languages). In contrast, a list would be ordered in Python.

I also feel that we should consider consistency with the `roombookings/rooms` endpoints - since the data is so similar, it seems a little strange to me that there are different approaches on the two endpoints.

I can't really think of a use case where you'd want to access the events grouped by day? I would have thought that if you were looking for something like this (e.g. alerting a student of the classes they have today), you would just limit your query to that day. I think there are also use cases where the 'date-as-key' approach makes things harder. For instance, imagine filling a database through the Django ORM with a `DateTimeField`. With ISO timestamps, you can just fill them straight in:

```python
In [1]: from mysite.models import Event

In [2]: ev = Event(dt="2016-09-02T09:00:00+00:00")

In [3]: ev.save()

In [4]: ev = Event.objects.all()[0]

In [5]: ev.dt.date()
Out[5]: datetime.date(2016, 9, 2)
```

With the current setup, it's going to be some kind of two-stage process, either concatenating the strings together or creating a `datetime` object from bits of the date and time strings.

Obviously if there are use cases where having the date as a key is useful, that could make sense - but for the use cases I can think of, it's probably easier just to have the date and time as a value rather than using a date as a key 😄

**Comment by ChristopherHammond13** [comment]
@keelanfh @tiferrei Thanks for your comments on this! There's some work I want to do on the Timetable API to improve it from several angles (including performance... *whistles* here, Redis! Come here boy!)

I think there's a lot of conflict on what people expect the Timetable API to output and why. For example, beginners may find the data grouped by data more useful, whereas more advanced users may wish an unordered list of sets of events that can be queried by the inner attributes. Both are legitimate ways to handle the data, and the answer ultimately will probably be to offer several output permutations.

**Comment by ChristopherHammond13** [comment]
Since this issue is stale I'm going to close it for now. We'll bear the comments in mind when creating new APIs, or making breaking changes to current ones. Thank you! 💖 🎉
