### ISSUE TITLE
[MIGRATION] travis-ci.org to Github Actions before Brexit

### ISSUE THREAD

**Issue by greenfrogs** [uclapi/uclapi#2955]
**Describe the  migration**
Travis-ci.org is being shutdown on December 31st, 2020. Repositories need to be migrated to travis-ci.com:
https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by hueyy** [comment]
Travis might be cutting back on its free credits for OSS projects:

[![tweet](https://user-images.githubusercontent.com/6523121/101483328-fd24fc00-3992-11eb-857f-12e6f02aedca.png)](https://twitter.com/james_hilliard/status/1336081776691843072)

Might be wise to consider moving off Travis altogether, maybe onto Github actions?

**Comment by zipy124** [comment]
Yeh as shown above by @hueyy it seems travis is getting ready to pull an Oracle and get rid of its free tier. We should definetly be moving to actions or another provider, or running our own build server at a last resort. Its quite possible we could use the apps server for it since it doesn't get much use.

**Comment by hueyy** [comment]
I think GitHub Actions should be a safe choice. In the unlikely scenario GitHub starts charging for it, [we can always run our own task runner on the apps server](https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners).
