### ISSUE TITLE
Query repeated twice.

### ISSUE THREAD

**Issue by Maaarcocr** [uclapi/uclapi#46]
So I was reading the source code and I found that [this](https://github.com/uclapi/uclapi/blob/master/backend/uclapi/roombookings/views.py#L128) and [this](https://github.com/uclapi/uclapi/blob/master/backend/uclapi/roombookings/helpers.py#L50) are called for the same api call and they seem to do the exact same query. Now, it could also be that I don't understand Python, so I'm sorry if this happens to be totally wrong.

**Comment by abdulfaizp** [comment]
Hi @maaarcocr pizza, 
First query is not evaluated when I create it, it's lazy evaluation. So they don't evaluate anything until I actually call the objects. Second query makes use of a database API to count the number of objects efficiently. Using `len` will result in evaluating the entire query which in effect would work against the idea of pagination. But you are right, I can use the `all_bookings` and apply `.Count()` on it.  Which is syntactically shorter but in terms of efficiency, we get the same result. I felt like explicitly stating the query would be more clearer when calling he `.count()` method. Feel free to make a PR if you feel otherwise.

**Comment by Maaarcocr** [comment]
[this](https://docs.djangoproject.com/en/1.10/ref/models/querysets/#django.db.models.query.QuerySet.count) seems to indicate that what I'm saying is correct, specifically when they mention that len is faster if you already have the objects in memory. 
Also, I've read about the queryset being lazy, but here it seems to me that you are making two query sets, not just modifying one.

**Comment by abdulfaizp** [comment]
@Maaarcocr that link actually talks about the case when if you have all the objects are retrieved from the database and saved it in the memory. then obviously `len` would be a more efficient operation. What `_paginated_result` does is, it creates a lazy evaluation of all the the bookings for that query, and only pull the results for the current page we need. which means, we don't have the entire query being made to the database. so although, `all_bookings = Booking.objects.using('roombookings').filter(**query)` is being created for each request, we don't actually make such a large query to the database, instead the `Paginator` updates the query to a smaller subset for efficient database hit. 

btw `count` field is the total number of bookings for the query being made. which is only returned with the first response to give the api consumer an idea of how long the results will be.

**Comment by Maaarcocr** [comment]
Oh okay, I didn't know about the Paginator!
