### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by adamfaliq42** [uclapi/uclapi#498]
I'd like to add license and contributing section in the README.md as that would be very helpful for future contributors. In addition, add a README.md in each folder, describing what the folder is for.

**Comment by ChristopherHammond13** [comment]
These are both reasonable suggestions. We should definitely decide upon a licence. I'm actually open to suggestions on which licence would be best for a project like this because I know very little about licensing.

**Comment by adamfaliq42** [comment]
You can see the list here, https://choosealicense.com/licenses/. Generally, GNU GPLv3 is quite restrictive whereas MIT License is more permissive. I'm concerned about the license because some apps can directly access staff/student's emails, which could be a tricky issue.

**Comment by ChristopherHammond13** [comment]
I just checked the repo and it seems that we're already [licensed under MIT ](https://github.com/uclapi/uclapi/blob/master/LICENSE) - I forgot that we'd done this! 

Generally, I'm happy with people doing whatever they want with the code (e.g. learning from it, forking and submitting patches, etc. - in fact, I'd support all these use cases). It's a weird situation with UCL API in that getting the data that makes it useful, such as the room bookings or student data, requires database access to be provisioned by UCL ISD. It's possible to set up a local instance of the code (and indeed that's what we do) but all the source data comes from protected data sources that are configured in our `.env` file.

Because everything except the frontend is hard to develop without being part of the team with database access we've not spent too long documenting how the project goes together. I expect I'll do a lot more of this in advance of new starters joining our team at some point in the coming months but I don't have any plans to handle this too soon due to the sheer volume of the task. There's also some weird bits of the code that all call one another (e.g. parts of the Timetable API rely on models imported from the `dashboard` and `roombookings` sub-apps within the Django project); unpicking all this is quite a large task.

I'm going to close this issue for now but I'll certainly be looking into documenting the structure of the code in the future. Thanks so much for raising this! :)
