### ISSUE TITLE
OAuth: No Error Message for Invalid Callback URLs

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/uclapi#945]
1) Create a new OAuth app in the Dashboard
2) Save an invalid callback URL, e.g. localhost
3) No Error
4) ???
5) Failure

**Comment by zipy124** [comment]
whats the criteria for it to be a valid callback URL?

**Comment by hueyy** [comment]
We could blacklist some URLs: e.g. localhost, 127.0.0.1, etc but unless we make a server-side request at that point in time, I don't think we can conclusively verify the URL is valid.

The way I see it, we have 3 options (in ascending order of effort & descending order of "correctness"):

1. Do simple frontend validation: check a blacklist and use regex or something to ensure the URL looks right.
2. Make an AJAX request on the frontend and check if the URL returns valid data
3. Set up a API endpoint on the backend to verify OAuth callback URLs by making a GET request and checking to see if valid data is returned.

However, if we do plan to support native apps (e.g. on mobile), we might only be able to validate with regex (option 1) because we would need to allow custom app URIs as callbacks (e.g. `roombuddy://callback`)
