### ISSUE TITLE
There is no logout button on the dashboard?!?!

### ISSUE THREAD

**Issue by zipy124** [uclapi/uclapi#970]
how has no one mentioned this before?

**Comment by zipy124** [comment]
so there's no way of switching between ucl accounts on the dashboard? since that would require logging out of shibboleth?

**Comment by ChristopherHammond13** [comment]
@zipy124 correct. The way to do it right now is to delete local session tokens for both us *and* UCL, and then log in again. Even if you go to `https://uclapi.com/Shibboleth.sso/Logout`, it will only kill the session token for Shibboleth on our servers (assuming you haven't switched servers via the load balancer as the sticky window is only 5 minutes until Dockerisation is rolled out). That means clicking Dashboard will still go:
- `/dashboard`/
- `/Shibboleth.sso/Login?target=/dashboard/shibcallback`
- UCL Sign in
- UCL's session will automatically log you in
- `/dashboard/shibcallback`
- `/dashboard` with the same account as before

(uclapi.com omitted from above URLs for brevity)

**Comment by ChristopherHammond13** [comment]
Can't fix won't fix will never fix sorry not sorry?

**Comment by Feverfew** [comment]
When this issue was opened, we did not have a logout button at all. Now we have a logout button. As briefly discussed in #2170, I now believe that neither solution is satisfactory from a security point of view.

Having no logout button at all does not allow a user to logout from their session (obviously).

Having a logout button gives a false sense of security, as one can log back in, without credentials, as Shibboleth would still have your session.

A sensible compromise would be to allow logout, but to then make it clear that further action is needed to achieve a _proper_ logout (i.e., close your browser window). @TuxedoFish came up with a simple javascript alert, something nicer should be aimed for. I won't comment on aesthetics, but whatever conveys the point clearly, isn't terrifyingly ugly and can't be missed, I'll approve

**Comment by TuxedoFish** [comment]
@Feverfew I agree I wasn't actually aware of the fact that Shibboleth would still have your session but now that I do, it seems like the best of the options to have a logout button but to alert the user that they need to take extra steps.

The javascript alert was definitely not the best solution, I thought it could work temporarily until we make a new page but I get that this seems a bit ugly!! I will have a go at creating a page that has a warning like this and tag it here once I open it!
